### ISSUE TITLE
Logo above navbar not resizing on mobile

### ISSUE THREAD

**Issue by jeffrey-zang** [jeffrey-zang/happy-math-education#7]
![image](https://user-images.githubusercontent.com/66485719/180298367-7ad5eca8-1711-425a-af57-ab8962b72d8f.png)

**Comment by Yourself1011** [comment]
Logo very chonky. Logo cause x-overflow![Screenshot_20220728-002408.png](https://user-images.githubusercontent.com/57602332/181420061-ed78c9ce-f128-428c-80d5-0b5d55a9fb27.png)

**Comment by jeffrey-zang** [comment]
chonk
